#Name: Joshua Wilkinson
#Date: 18/10/2023
#Purpose: Make file for lab 5
#See http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/ for info on make files.


CC=g++
CFLAGS= -std=c++11 -pthread
CPPFILES=main.cpp Semaphore.cpp

SIMPLE: $(CPPFILES)
	g++ -std=c++11 -pthread $(CPPFILES)


CLEAN:
	rm *.o
