Lab 6: sort/quicksort.cpp File Reference
quicksort.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <complex>
#include <time.h>
#include <functional>
#include <limits>
#include <vector>
Functions
int partition (vector< int > &myArray, int low, int high)
int quicksort (vector< int > &myArray, int low, int high)
int main (void)
Variables
const int LENGTH =2000
Function Documentation
main()
int main (void)
Sorting large amounts of data can be time consuming, but by utilising parallel algorithms, we can break down the sorting process into smaller, more manageable chunks, that can be executed simultaneously.
Definition at line 108 of file quicksort.cpp.
{
  srand (time(NULL));
  vector<int> data(LENGTH);
  for(auto& value:data){
    value=rand()%1000;
  }
  for(auto& value:data){
    cout<<value<<" ";
  }
  cout << endl<<"*******************************"<<endl;
  quicksort(data,0,data.size()-1);
  for(auto& value:data){
    cout<<value<<" ";
  }
  cout << endl;
}
partition()
int partition (vector< int > & myArray, int low, int high)
Quicksort is a divide and conquer algorithm that works by selecting a pivot element from the array and partitioning the other elements into two sub arrays, according to whether they are less than or greater than the pivot. The sub arrays are then recursively sorted.
Definition at line 62 of file quicksort.cpp.
{
  int pivot=myArray[high];
  int k=high;
  int i=low;
  int temp=0;
  while (i<k){
    while (myArray[i]<pivot && i<k)++i;
    while (myArray[k]>pivot && i<k)--k;
    if (i<k){
      temp=myArray[i];
      myArray[i]=myArray[k];
      myArray[k]=temp;
      i++;//do not decrement k here OR ELSE!!
    }
  }
  return i-1;
}
Referenced by quicksort().
quicksort()
int quicksort (vector< int > & myArray, int low, int high)
This method calls the pivot and does the actual sorting.
Definition at line 89 of file quicksort.cpp.
{
  if (low<high){
    int pivot=partition(myArray,low,high);
    //really we should only do this if each partition is above a certain size (1000 elements?)
    //otherwise the overhead outweighs any gains from using threads
    #pragma omp task shared(myArray)
    quicksort(myArray,low,pivot);
    quicksort(myArray,pivot+1,high);
    #pragma omp taskwait
  return 1;
  }
  return 0;
}//quicksort
Referenced by main(), and quicksort().
Variable Documentation
LENGTH
const int LENGTH =2000
Definition at line 59 of file quicksort.cpp.
Referenced by main().