Lab 6: map-reduce/reduction.cpp File Reference
reduction.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <complex>
#include <time.h>
#include <functional>
#include <limits>
#include <vector>
#include <omp.h>
Functions
int get_num_threads (void)
! Find out how many threads are running!
float getSerialSum (vector< int > data)
float getParallelSum (vector< int > data)
float getTiledParallelsum (vector< int > data)
int main (void)
Variables
const int LENGTH =2000
int NumThreads =1
Function Documentation
get_num_threads()
int get_num_threads (void)
! Find out how many threads are running!
Definition at line 64 of file reduction.cpp.
{
    int num_threads = 1;
    //must ask in parallel region otherwise 1 is returned
    #pragma omp parallel
    {
        #pragma omp single
        num_threads = omp_get_num_threads();
    }
    return num_threads;
}
Referenced by getTiledParallelsum().
getParallelSum()
float getParallelSum (vector< int > data)
Definition at line 83 of file reduction.cpp.
{
  float sum=0.0;
#pragma omp parallel for reduction(+:sum)
  for(int i=0;i<data.size();++i){
    sum+=data[i];
  }
  return sum;
}
Referenced by main().
getSerialSum()
float getSerialSum (vector< int > data)
Definition at line 75 of file reduction.cpp.
{
  float sum=0.0;
  for(auto& value:data){
    sum+=value;
  }
  return sum;
}
Referenced by main().
getTiledParallelsum()
float getTiledParallelsum (vector< int > data)
Definition at line 93 of file reduction.cpp.
{
  float result =0.0;
  NumThreads=get_num_threads();
  float tileResult[NumThreads];
  for(int i=0;i<NumThreads;++i) tileResult[i]=0.0;
  //map step here
#pragma omp parallel for
  for (int i=0; i < data.size(); ++i ){
    int tid = omp_get_thread_num();
    tileResult[tid] =tileResult[tid]+data[i];
  }
  //reduce step here
  for (int i=0; i < NumThreads ; ++i ){
    std::cout << i<< ":"<< tileResult[i] << "- ";
    result+=tileResult[i];
  }
  std::cout <<std::endl;
  return result ;
}
Referenced by main().
main()
int main (void)
Map/Reduce is the process of mapping a function to one or more arrays of data, and then reducing the result back to a single value. Map/Reduce in inherently parallelisable, as we will discover in this program.
The benefit of this over a seperate map and then reduce, is that we do not need to create the itermediate vector results from the map. Results from the map can immediately fed into the reduce as they are available.
Definition at line 115 of file reduction.cpp.
              {
  float sum=0.0;
  int average=0;
  NumThreads=omp_get_num_threads();
  srand (time(NULL));
  vector<int> data(1000);
  for(auto& value:data){
    value=10;//rand()%1000;
  }
  sum=getSerialSum(data);
  average=sum/data.size();
  cout <<"Serial Average is: "<<average<<endl;
  sum=getParallelSum(data);
  average=sum/data.size();
  cout <<"Parallel Average is: "<<average<<endl;
  cout << endl;
  sum=getTiledParallelsum(data);
  average=sum/data.size();
  cout <<"Parallel Average is: "<<average<<endl;
  cout << endl;
}
Variable Documentation
LENGTH
const int LENGTH =2000
Definition at line 59 of file reduction.cpp.
NumThreads
int NumThreads =1
Definition at line 60 of file reduction.cpp.
Referenced by getTiledParallelsum(), and main().