Lab 5: main.cpp File Reference
main.cpp File Reference
#include "Semaphore.h"
#include <iostream>
#include <thread>
#include <vector>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
Functions
std::vector< std::shared_ptr< Semaphore > > forks (COUNT)
void think (int myID)
void get_forks (int philID)
void put_forks (int philID)
void eat (int myID)
void philosopher (int id)
int main (void)
Variables
const int COUNT = 5
const int THINKTIME =3
const int EATTIME =5
std::shared_ptr< Semaphore > stopper
Function Documentation
eat()
void eat (int myID)
The philosopher eats for a random amount of time
Definition at line 76 of file main.cpp.
                  {
  int seconds=rand() % EATTIME + 1;
  std::cout << myID << " is chomping! "<<std::endl;
  sleep(seconds);
}
Referenced by philosopher().
forks()
std::vector< std::shared_ptr< Semaphore > > forks (COUNT)
Referenced by get_forks(), main(), and put_forks().
get_forks()
void get_forks (int philID)
A philosopher searches for a fork to their left and to their right
Definition at line 58 of file main.cpp.
{
  stopper->Wait(); // will block when 4 threads have reached this line
  std::cout << philID << " is getting their forks!" << std::endl;
  forks[philID]->Wait();
  std::cout << philID << " has gotten their fork!" << std::endl;
  forks[(philID+1)%COUNT]->Wait();
  std::cout << philID << " has gotten their fork!" << std::endl;
}
Referenced by philosopher().
main()
int main (void)
< iterates through the forks vector array to make the Semaphore property (1).
< can withstand 4 waits before blocking
Definition at line 94 of file main.cpp.
              {
  for (int i = 0; i < COUNT; ++i){
    forks[i] = std::make_shared<Semaphore>(1);
  }
  srand (time(NULL)); // initialize random seed:
  std::vector<std::thread> vt(COUNT);
  stopper = std::make_shared<Semaphore>(4);
  int id=0;
  for(std::thread& t: vt){
    t=std::thread(philosopher,id++/*,params*/);
  }
  for (auto& v :vt){
      v.join();
  }
  return 0;
}
philosopher()
void philosopher (int id)
runs the dinner service for the philosophers for a set amount of time
Definition at line 83 of file main.cpp.
{
  int times=10; // Number of times the philosphers sit down to eat!
  while(times>0){
    think(id);
    get_forks(id);
    eat(id);
    put_forks(id);
    times--;
  }//while
}//philosopher
Referenced by main().
put_forks()
void put_forks (int philID)
A philosopher puts down both of their forks, ready for the next philospher process
Definition at line 68 of file main.cpp.
{
  std::cout << philID << " is putting their forks down!" << std::endl;
  forks[philID]->Signal();
  forks[(philID+1)%COUNT]->Signal();
  stopper->Signal(); // will signal when a thread has finished eating, letting other processes go through
}
Referenced by philosopher().
think()
void think (int myID)
A philosopher thread is given a random time to think before searching for forks
Definition at line 51 of file main.cpp.
                    {
  int seconds=rand() % THINKTIME + 1;
  std::cout << myID << " is thinking! "<<std::endl;
  sleep(seconds);
}
Referenced by philosopher().
Variable Documentation
COUNT
const int COUNT = 5
Definition at line 44 of file main.cpp.
Referenced by get_forks(), main(), and put_forks().
EATTIME
const int EATTIME =5
Definition at line 46 of file main.cpp.
Referenced by eat().
stopper
std::shared_ptr<Semaphore> stopper
Definition at line 48 of file main.cpp.
Referenced by get_forks(), main(), and put_forks().
THINKTIME
const int THINKTIME =3
Definition at line 45 of file main.cpp.
Referenced by think().